### ISSUE TITLE
Error in the code?

### ISSUE THREAD

**Issue by theredcat** [glaszig/node-dhcpd#5]
Hi,

I've spotted this in the code (lib/packet.js +113): <code>buffer.write(this.fname, 109, 128, 'ascii');</code>

However, there is no definition for <code>this.fname</code>

Shouldn't this be removed? (And find a way to handle this in Forge? :) )

**Comment by glaszig** [comment]
please link the file and line. in `packet.js` i only found [one occurrence of `fname`](https://github.com/glaszig/node-dhcpd/blob/master/lib/packet.js#L83) and i think it's ok.

**Comment by theredcat** [comment]
Yea I was talking about this one. But there is a problem here : if you do a buffer.write in an undefined var, node will throw an exception.

You should take a look on this fork : https://github.com/chipzz/node-dhcpd/commit/64926e865f8d96da661fd3122fdd004db42b4e6c

I'm using it and it fixes all my problems. The interesting part is the first part of the commit on packet.js.

**Comment by glaszig** [comment]
alright. maybe @chipzz wants to pr his branch?

**Comment by chipzz** [comment]
the branch published there was WIP, I had more WIP in more working directory. Committed it all and pushed. You want to look at https://github.com/chipzz/node-dhcpd/commit/1736ddb7badc35b493bf9000eca9bd8e22a91e56 instead. Shall I do a PR for that?

**Comment by glaszig** [comment]
@chipzz sure. i like the converter refactoring.

**Comment by chipzz** [comment]
https://github.com/glaszig/node-dhcpd/pull/6
